import { db } from "../../../lib/db.js";
import { GoogleGenerativeAI } from "@google/generative-ai";

/**
 * Gemini client.
 */
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

/**
 * Generate and save lesson objectives for a topic.
 *
 * The topic's lessonContents are used as the primary curriculum
 * source. Gemini is instructed to generate approximately five
 * progressive learning objectives.
 *
 * The system does NOT require exactly five objectives.
 * If Gemini returns fewer or more than five valid objectives,
 * the valid objectives are still saved and used.
 *
 * @param {Object} topic
 * @returns {Promise<Array>} Saved TopicObjective records.
 */
export async function generateTopicObjectives(topic) {
  if (!topic?.id) {
    const error = new Error("A valid topic is required.");
    error.statusCode = 400;
    throw error;
  }

  if (
    !Array.isArray(topic.lessonContents) ||
    topic.lessonContents.length === 0
  ) {
    const error = new Error(
      "This topic does not contain lesson contents for objective generation."
    );

    error.statusCode = 400;

    throw error;
  }

  /*
   * Check again before calling Gemini.
   *
   * Another request may have generated the objectives after
   * ensureTopicObjectives() performed its initial check.
   */
  const existingObjectives = await db.topicObjective.findMany({
    where: {
      topicId: topic.id,
    },
    orderBy: {
      order: "asc",
    },
  });

  if (existingObjectives.length > 0) {
    return existingObjectives;
  }

  const model = genAI.getGenerativeModel({
    model: process.env.GEMINI_TUTOR_MODEL || "gemini-2.5-flash",
    generationConfig: {
      temperature: 0.3,
      responseMimeType: "application/json",
    },
  });

  /*
   * Convert lesson contents into a numbered curriculum source.
   */
  const lessonContents = topic.lessonContents
    .map((content, index) => `${index + 1}. ${content}`)
    .join("\n");

  const subjectName = topic.subject?.name || "Unknown subject";
  const className = topic.class?.name || "Unknown class";
  const termName = topic.term?.name || "Unknown term";

  const prompt = `
    You are an experienced curriculum teacher creating structured
    lesson objectives for an educational platform.

    Create approximately 5 progressive learning objectives for the
    topic below.

    The number does not have to be exactly 5. Depending on the amount
    and complexity of the lesson content, you may generate fewer or
    more than 5 objectives when that produces a better educational
    sequence.

    CURRICULUM INFORMATION

    Class:
    ${className}

    Subject:
    ${subjectName}

    Term:
    ${termName}

    Topic:
    ${topic.title}

    LESSON CONTENTS

    ${lessonContents}

    INSTRUCTIONS

    1. Base the objectives primarily on the supplied lesson contents.
    2. Do not introduce unrelated concepts.
    3. Keep the objectives appropriate for the specified class level.
    4. Arrange the objectives from foundational understanding to application.
    5. Each objective must represent something the student can reasonably learn.
    6. Avoid duplicate or substantially overlapping objectives.
    7. Use clear language suitable for a school student.
    8. Each objective must be specific enough for an AI Tutor to teach independently.
    9. Collectively cover the important lesson contents.
    10. Do not mention that the objectives were generated by AI.
    11. Generate approximately five objectives.
    12. Return at least one objective.
    13. The order should represent the recommended teaching sequence.

    Return ONLY valid JSON using this structure:

    {
      "objectives": [
        {
          "order": 1,
          "title": "Objective title",
          "description": "What the student should understand or be able to do."
        },
        {
          "order": 2,
          "title": "Objective title",
          "description": "What the student should understand or be able to do."
        }
      ]
    }
  `;

  let result;

  try {
    result = await model.generateContent(prompt);
  } catch (error) {
    console.error(
      "Gemini objective generation failed:",
      error
    );

    const generationError = new Error(
      "Unable to generate lesson objectives at this time."
    );

    generationError.statusCode = 503;

    throw generationError;
  }

  const responseText =
    result?.response?.text?.()?.trim();

  if (!responseText) {
    const error = new Error(
      "Gemini returned an empty objective response."
    );

    error.statusCode = 502;

    throw error;
  }

  let parsedResponse;

  try {
    parsedResponse = JSON.parse(responseText);
  } catch (error) {
    console.error(
      "Invalid JSON returned by Gemini:",
      responseText
    );

    const parseError = new Error(
      "Gemini returned an invalid objective response."
    );

    parseError.statusCode = 502;

    throw parseError;
  }

  /*
   * Validate the overall response structure.
   */
  if (
    !parsedResponse ||
    !Array.isArray(parsedResponse.objectives)
  ) {
    const error = new Error(
      "Gemini returned an invalid objective structure."
    );

    error.statusCode = 502;

    throw error;
  }

  const generatedObjectives = parsedResponse.objectives;

  /*
   * We no longer require exactly five objectives.
   *
   * However, we must have at least one valid objective.
   */
  if (generatedObjectives.length === 0) {
    const error = new Error(
      "Gemini did not generate any lesson objectives."
    );

    error.statusCode = 502;

    throw error;
  }

  /*
   * Validate and normalize every objective.
   *
   * We intentionally ignore the order supplied by Gemini and
   * assign the database order based on the returned sequence.
   */
  const validatedObjectives = [];

  for (const objective of generatedObjectives) {
    if (!objective || typeof objective !== "object") {
      continue;
    }

    if (
      typeof objective.title !== "string" ||
      !objective.title.trim()
    ) {
      continue;
    }

    if (
      typeof objective.description !== "string" ||
      !objective.description.trim()
    ) {
      continue;
    }

    validatedObjectives.push({
      title: objective.title.trim(),
      description: objective.description.trim(),
    });
  }

  /*
   * If Gemini returned objects but none of them contained
   * usable data, fail because there is nothing meaningful
   * that can be stored.
   */
  if (validatedObjectives.length === 0) {
    const error = new Error(
      "Gemini did not return any valid lesson objectives."
    );

    error.statusCode = 502;

    throw error;
  }

  /*
   * Remove duplicate objective titles.
   *
   * This keeps the generated curriculum clean even if Gemini
   * accidentally repeats an objective.
   */
  const uniqueObjectives = [];
  const seenTitles = new Set();

  for (const objective of validatedObjectives) {
    const normalizedTitle = objective.title
      .trim()
      .toLowerCase();

    if (seenTitles.has(normalizedTitle)) {
      continue;
    }

    seenTitles.add(normalizedTitle);
    uniqueObjectives.push(objective);
  }

  if (uniqueObjectives.length === 0) {
    const error = new Error(
      "No unique lesson objectives were generated."
    );

    error.statusCode = 502;

    throw error;
  }

  /*
   * Assign a clean sequential order ourselves.
   *
   * This guarantees:
   *
   * 1
   * 2
   * 3
   * 4
   * ...
   *
   * regardless of the order values returned by Gemini.
   */
  const objectivesToSave = uniqueObjectives.map(
    (objective, index) => ({
      topicId: topic.id,
      title: objective.title,
      description: objective.description,
      order: index + 1,
      source: "AI_GENERATED",
    })
  );

  /*
   * Save all objectives.
   *
   * The @@unique([topicId, order]) constraint in Prisma protects
   * the topic from duplicate objective positions.
   */
  try {
    await db.topicObjective.createMany({
      data: objectivesToSave,
      skipDuplicates: true,
    });
  } catch (error) {
    console.error(
      `Failed to save objectives for topic ${topic.id}:`,
      error
    );

    const databaseError = new Error(
      "Unable to save the generated lesson objectives."
    );

    databaseError.statusCode = 500;

    throw databaseError;
  }

  /*
   * Always retrieve the persisted records.
   *
   * This ensures the caller receives the actual database state.
   */
  const savedObjectives = await db.topicObjective.findMany({
    where: {
      topicId: topic.id,
    },
    orderBy: {
      order: "asc",
    },
  });

  if (savedObjectives.length === 0) {
    const error = new Error(
      "Lesson objectives could not be retrieved after generation."
    );

    error.statusCode = 500;

    throw error;
  }

  return savedObjectives;
}
