export const ACADEMIC_SUBJECTS = [
  "mathematics and numeracy",
  "english",
  "Phonics and pronunciation",
  "literature-in-english",
  "Basic Science",
  "Basic Technology",
  "Physical and Health Education",
  "Home Economics",
  "Music",
  "Fine and Creative Art",
  "Business Studies",
  "Social Studies",
  "Security Education",
  "Yoruba/Igbo/Hausa/French Language",
  "History",
  "physics",
  "chemistry",
  "biology",
  "economics",
  "history",
  "geography",
  "agricultural science",
  "commerce",
  "government",
  "literature",
  "computer science",
  "civic education",
  "social studies",
  "further mathematics",
  "accounting",
];