export const XP = {
    MILLIONAIRE: {
        PARTICIPATION: 20,
        PER_CORRECT: 10,
        LEVEL_REACHED: 5,
        COMPLETION_BONUS: 150,
    },

    SPEED_CHALLENGE: {
        PARTICIPATION: 15,
        PER_CORRECT: 8,
        ACCURACY_90: 75,
        ACCURACY_100: 120,
    },

    DAILY_CHALLENGE: {
        COMPLETION: 100,
    },
};

export const SUBJECT_LEVEL_XP = 500;

export const ACCOUNT_LEVEL_XP = 1000;

export const ACHIEVEMENT_CODES = {
    FIRST_VICTORY: "FIRST_VICTORY",
    LEVEL5_SURVIVOR: "LEVEL5_SURVIVOR",
    LEVEL10_MASTER: "LEVEL10_MASTER",
    MILLIONAIRE_CHAMPION: "MILLIONAIRE_CHAMPION",
    HIGH_ROLLER: "HIGH_ROLLER",
    SPEED_DEMON: "SPEED_DEMON",
    QUESTION_MASTER: "QUESTION_MASTER",
    SEVEN_DAY_STREAK: "SEVEN_DAY_STREAK",
    LEVEL10_SCHOLAR: "LEVEL10_SCHOLAR",
};

export const DAILY_CHALLENGE_CODES = {
  COMPLETE_ONE_MILLIONAIRE_GAME:
    "COMPLETE_ONE_MILLIONAIRE_GAME",

  COMPLETE_ONE_SPEED_CHALLENGE:
    "COMPLETE_ONE_SPEED_CHALLENGE",

  COMPLETE_ONE_AI_LESSON:
    "COMPLETE_ONE_AI_LESSON",

  STUDY_20_FLASHCARDS:
    "STUDY_20_FLASHCARDS",
};